version: "3.8"
services: 
  chrome-server:
    profiles: ["extractor-server"]
    image: "selenium/standalone-chrome:latest"
    ports:
      - 4444
      - "7900:7900"

  extractor:
    profiles: ["extractor"]
    depends_on:
      - chrome-server
    volumes:
      - ./logs:/opt/logs
    environment:
      DRIVER_URL: "http://chrome-server:4444"
    build:
      context: .

  tobserver:
    profiles: ["analysis"]
    image: lazarodm/tobstt
    ports:
    - "5005:5005"
    depends_on:
    - dbserver
    entrypoint: ["rasa", "run", "-p", "5005", "--enable-api", "--auth-token", "jupytertob", "--connector", "rest"]
    environment:
      TELEGRAM_ACCESS_TOKEN: 5999970947:AAH2gdRM9ZfgQuD_5Qh2Mg6BCFtgqndG14w
      TELEGRAM_BOT_USERNAME: tobstt_dev_bot
      TELEGRAM_WEBHOOK_URL: https://tobsttdeverun.loca.lt/webhooks/telegram/webhook
      MONGO_DB_SERVER: mongodb://dbserver:27017
    volumes:
      - /home/lazaro/dev/tob-stt/rasa-bot/models:/tob-stt/models
    deploy:
      resources:
        reservations:
          devices:
          - capabilities: [gpu]

  dbserver:
    image: mongo
    profiles: ["analysis"]
    volumes:
      - /home/lazaro/dev/tob-stt/rasa-bot/db:/data/db

  jupyter:
    profiles: ["analysis"]
    build:
      context: .
      dockerfile: Dockerfile-Analysis
    ports:
      - "8888:8888"
    volumes:
      - ./logs:/home/jovyan/work
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            count: all
            capabilities: [gpu]

