version: "3.8"
services: 
  chrome-server:
    profiles: ["extractor-server"]
    image: "selenium/standalone-chrome:latest"
    ports:
      - 4444
      - "7900:7900"
  extractor:
    profiles: ["extractor"]
    depends_on:
      - chrome-server
    volumes:
      - ./logs:/opt/logs
    environment:
      DRIVER_URL: "http://chrome-server:4444"
    build:
      context: .
  jupyter:
    profiles: ["analysis"]
    image: jupyter/datascience-notebook:2023-07-31
    ports:
      - "8888:8888"
    volumes:
      - ./logs:/home/jovyan/work
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]

